name: "Cached LFS checkout with submodules"

description: "Git checkout with LFS files from cache with submodules"

branding:
  icon: "download"
  color: "green"

inputs:
  repository:
    description: "Repository name with owner"
    required: false
    default: ${{ github.repository }}
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
  token:
    description: "PAT used to fetch the repository"
    required: false
    default: ${{ github.token }}
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    required: false
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags"
    required: false
    default: 1
  submodules:
    description: "Whether to checkout submodules. Accepted values are: true, false, recursive"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}

    - name: Create LFS file list
      if: runner.os != 'Windows' && inputs.submodules == 'false'
      working-directory: ${{ inputs.path }}
      run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
      shell: bash
    
    - name: Create LFS file list with submodules
      if: runner.os != 'Windows' && inputs.submodules != 'false'
      working-directory: ${{ inputs.path }}
      run: |
        git lfs ls-files -l | cut -d' ' -f1 > .lfs-assets-id
        git submodule foreach --recursive 'git lfs ls-files -l' | cut -d' ' -f1 >> .lfs-assets-id
        grep -v Entering .lfs-assets-id | sort > .temp
        mv .temp .lfs-assets-id
      shell: bash

    - name: Create LFS file list (Windows)
      if: runner.os == 'Windows' && inputs.submodules == 'false'
      working-directory: ${{ inputs.path }}
      run: |
        git lfs ls-files -l > totalLFS.txt
        $lines = Get-Content ".\totalLFS.txt"
        foreach ($line in $lines){Out-File -FilePath "splitLFS.txt" -Append -InputObject ($line.Split(" "))[0]}
        type .\splitLFS.txt | sort > .lfs-assets-id
        del .\splitLFS.txt
        del .\totalLFS.txt
      shell: PowerShell

    - name: Create LFS file list with submodules (Windows)
      if: runner.os == 'Windows' && inputs.submodules != 'false'
      working-directory: ${{ inputs.path }}
      run: |
        git lfs ls-files -l > totalLFS.txt
        git submodule foreach --recursive "git lfs ls-files -l" >> totalLFS.txt
        $lines = Get-Content ".\totalLFS.txt"
        foreach ($line in $lines){Out-File -FilePath "splitLFS.txt" -Append -InputObject ($line.Split(" "))[0]}
        type splitLFS.txt | findstr /v Entering | sort > .lfs-assets-id
        del .\splitLFS.txt
        del .\totalLFS.txt
      shell: PowerShell

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      if: runner.os != 'Windows' && inputs.submodules == 'false'
      working-directory: ${{ inputs.path }}
      run: git lfs pull
      shell: bash

    - name: Git LFS Pull with submodules
      if: runner.os != 'Windows' && inputs.submodules != 'false'
      working-directory: ${{ inputs.path }}
      run: |
        git lfs pull
        git submodule foreach --recursive 'git lfs pull'
      shell: bash

    - name: Git LFS Pull (Windows)
      if: runner.os == 'Windows' && inputs.submodules == 'false'
      working-directory: ${{ inputs.path }}
      run: git lfs pull
      shell: PowerShell

    - name: Git LFS Pull with submodules (Windows)
      if: runner.os == 'Windows' && inputs.submodules != 'false'
      working-directory: ${{ inputs.path }}
      run: |
        git lfs pull
        git submodule foreach --recursive 'git lfs pull'
      shell: PowerShell
